In [1]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
from sklearn.datasets import make_regression
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import StandardScaler
import pandas as pd

In [2]:
df = pd.read_csv("../data/combined.csv")
df

Race  HIV (non-AIDS) Rate  AIDS Rate  \
0  American Indian and/or Alaska Native                118.6      164.3   
1                                 Asian                 34.9       48.9   
2             Black or African American                370.1      595.5   
3                              Hispanic                 98.8      164.0   
4                            Mixed Race                 79.2       97.0   
5                                 White                136.3      208.3   

   HIV/AIDS Rate  Infant Mortality Rate  Insurance Application Rate  \
0          282.9                   5.35                        1.88   
1           83.8                   2.95                        3.28   
2          965.7                  11.12                        5.66   
3          262.8                   5.07                        4.98   
4          176.1                  10.94                        3.09   
5          344.5                   4.26                        3.71   

   Disease Rate per 100,000  Poverty Rate  
0                    133.13          20.2  
1                     76.71          11.5  
2                    307.39          21.4  
3                     99.63          20.9  
4                     79.17          13.2  
5                     93.82           8.0

In [13]:
races = df['Race'].values.tolist()
predictions = [];

for race in races:
    X = df.loc[df['Race'] != race].iloc[:, [3, 4, 5, 6]].values
    
#     for array in X:
#         array = array.reshape(-1, 1)

    y = df.loc[df['Race'] != race]['Poverty Rate'].values.reshape(-1, 1)

    X_scaler = StandardScaler().fit(X)
    y_scaler = StandardScaler().fit(y)
    
    X_scaled = X_scaler.transform(X)
    y_scaled = y_scaler.transform(y)
    
    model = LinearRegression()
    model.fit(X_scaled, y_scaled)
    
    predictions.append(model.predict(df.loc[df['Race'] == race].iloc[:, [3, 4, 5, 6]].values))    

In [14]:
predictions

[array([[-398.48668457]]),
 array([[-22.56563202]]),
 array([[-383.23212219]]),
 array([[-77.29320153]]),
 array([[-662.68018772]]),
 array([[4132.0461712]])]

In [15]:
y = df['Poverty Rate'].values.reshape(-1, 1)

y_scaler = StandardScaler().fit(y)
y_scaled = y_scaler.transform(y)

y_scaled

array([[ 0.83191588],
       [-0.83831523],
       [ 1.06229259],
       [ 0.96630229],
       [-0.51194823],
       [-1.51024729]])

In [7]:
X = df.iloc[:, [3, 4, 5, 6]].values

y = df['Poverty Rate'].values.reshape(-1, 1)

X_scaler = StandardScaler().fit(X)
y_scaler = StandardScaler().fit(y)

X_scaled = X_scaler.transform(X)
y_scaled = y_scaler.transform(y)

model = LinearRegression()
model.fit(X_scaled, y_scaled)

X_scaled

array([[-0.24344885, -0.39363064, -1.5142407 ,  0.01843319],
       [-0.9385349 , -1.14043975, -0.39059919, -0.68033522],
       [ 2.14030178,  1.40182294,  1.51959137,  2.17666399],
       [-0.31362078, -0.48075837,  0.97382264, -0.3964683 ],
       [-0.61630264,  1.34581226, -0.54309339, -0.64986783],
       [-0.02839461, -0.73280644, -0.04548073, -0.46842584]])

In [19]:
X[0].reshape(-1,1)

array([[282.9 ],
       [  5.35],
       [  1.88],
       [133.13]])

In [17]:
y

array([[20.2],
       [11.5],
       [21.4],
       [20.9],
       [13.2],
       [ 8. ]])

In [4]:
race = 'Asian'

X = df.loc[df['Race'] != race].iloc[:, [3, 4, 5, 6]].values

#     for array in X:
#         array = array.reshape(-1, 1)

y = df.loc[df['Race'] != race]['Poverty Rate'].values.reshape(-1, 1)

X_scaler = StandardScaler().fit(X)
y_scaler = StandardScaler().fit(y)

X_scaled = X_scaler.transform(X)
y_scaled = y_scaler.transform(y)

model = LinearRegression()
model.fit(X_scaled, y_scaled)

model.predict(df.loc[df['Race'] == race].iloc[:, [3, 4, 5, 6]].values)

array([[-22.56563202]])

In [15]:
np.corrcoef(df['Poverty Rate'], [df['HIV/AIDS Rate'], df['Infant Mortality Rate'], 
                                 df['Insurance Application Rate'], df['Disease Rate per 100,000']])[0][1]

0.4855385507445113